FROM quay.io/pypa/manylinux2014_x86_64

# Install system dependencies
RUN yum -y update; yum clean all
RUN yum -y install epel-release.noarch; yum clean all
RUN yum -y update; yum -y install \
    gcc \
    gcc-c++ \
    cmake \
    git \
    gmp-devel \
    mpfr-devel \
    make \
    curl && \
    yum clean all

RUN curl -s -SL "https://archives.boost.io/release/1.84.0/source/boost_1_84_0.tar.gz" | tar xz -C /tmp && \
    cd /tmp/boost_1_84_0 && \
    ./bootstrap.sh --prefix=/usr/local --with-libraries=system,filesystem,program_options,iostreams,serialization,thread,date_time,chrono && \
    ./b2 -j 6 install && cd / && rm -rf /tmp/boost_1_84_0 && ldconfig

# Install CGAL
ARG CGAL_VERSION_TAG="v5.6"
RUN git clone --branch ${CGAL_VERSION_TAG} --depth 1 https://github.com/CGAL/cgal.git /app/cgal \
    && cd /app/cgal \
    && mkdir build \
    && cd build \
    && cmake  -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_POLICY_VERSION_MINIMUM=3.5 .. \
    && make install | (sed -u 20q;tail -n20) \
    && rm -rf /app/cgal

# Create working directories
RUN mkdir -p /app/output && chmod 777 /app/output

# For runnint tests. Move to build_wheel_entrypoint.sh for multiple Python versions building.
ARG PYTHON_VERSION_MINOR="10"
RUN python3.${PYTHON_VERSION_MINOR} -m pip install pytest matplotlib IPython

# Copy build script and set permissions
COPY include/  /app/scikit-geometry/include/
COPY skgeom/ /app/scikit-geometry/skgeom/
COPY src/ /app/scikit-geometry/src/
COPY test/ /app/scikit-geometry/test/
COPY setup.py /app/scikit-geometry
COPY docker/build_wheel_entrypoint.sh /app/scikit-geometry
RUN chmod +x /app/scikit-geometry/build_wheel_entrypoint.sh

WORKDIR /app/scikit-geometry
# Set the entrypoint
ENTRYPOINT ["./build_wheel_entrypoint.sh"]

